# Generated by Django 4.2.5 on 2023-09-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthmate_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
